### ISSUE TITLE
404s when installing using jspm (v16)

### ISSUE THREAD

**Issue by jfstephe** [michaelbull/aurelia-split-pane#2]
If people also have this problem this can be fixed by adding the following config to the packages section of your systemjs config.js file:

`
    "aurelia-split-pane": {
      "map": {
        "./split-pane": "./dist/split-pane",
        "./split-pane-divider": "./dist/split-pane-divider"
      }
    }
`

PS Nice component - thanks for creating! Feel free to close this as there is a workaround, I just wanted to have a record of it. :-)

**Comment by michaelbull** [comment]
Hi, thanks for the comment and feedback :)

Would you like to submit a PR to add these instructions to the README for others?

**Comment by jfstephe** [comment]
done :-)
