### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jfstephe** [michaelbull/aurelia-split-pane#4]
Hi,
I was wondering if you'd be ok with another PR to extend this to add an *optional* capability to minimise/restore a panel?

I'm thinking of optionally showing some buttons either side of the splitter which would only be shown when hovering over it.

I don't need this functionality ATM but I may do soon, just checking you'd be happy to include it.

John

**Comment by michaelbull** [comment]
Absolutely! Feel free to open a PR and I can review it whenever you'd like.
