### ISSUE TITLE
hide divider if only 1 child is visible

### ISSUE THREAD

**Issue by iramonCode** [michaelbull/aurelia-split-pane#5]
Hi, thanks for you compo!
I have the situation of a split panel with 2 elements, but the left element is not visible for small screens (I'm using aurelia-materialize and using  class="hide-on-med-and-down" to hide the 1rst panel).

I was going to check the screen size change events and update the properties of the divider (flex-basis: 0; ) when it becames small... do you have some suggestion for a better way to do that?

Thanks!
Daniel Calbet

**Comment by michaelbull** [comment]
Hi, thanks for your comments. Can you link me me to a working example that demonstrates the problem? Off the top of my head you could set the left panel's `min-width` property, something like:

```html
<template>
  <split-pane direction="horizontal">
    <div style="min-width: 200px;">left</div>
    <div>right</div>
  </split-pane>
</template>
```
