### ISSUE TITLE
Aurelia2 upgrade

### ISSUE THREAD

**Issue by MaximBalaganskiy** [michaelbull/aurelia-split-pane#7]
Are there plans to upgrade?

**Comment by michaelbull** [comment]
No plans as I don't use Aurelia anymore.

**Comment by MaximBalaganskiy** [comment]
@michaelbull can you please add me as a contributor to avoid cloning?

**Comment by michaelbull** [comment]
I would suggest forking and publishing to your own npm package. I am not comfortable giving publish rights for my packages to others.
